[#780] If clause to run on python3.8 on ubuntu-22.04 with GH actions.
Signed-off-by: Maksim Gelbakhiani <max@nspcc.ru>

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -29,7 +29,7 @@ case "$ID" in
         done
 
         if [ -n "$missing" ]; then
-            echo "$0: Missing required packages: ${missing}." 1>&2  
+            echo "$0: Missing required packages: ${missing}." 1>&2
             sudo pacman -S $missing
         fi
         ;;
@@ -71,8 +71,12 @@ case "$ID" in
 esac
 
 
-# s3-tests only works on python 3.6 not newer versions of python3
-${virtualenv} --python=$(which python3.6) virtualenv
+# s3-tests should work on python 3.6 or 3.8 not newer versions of python3
+if [ $(which python3.6) ]; then
+    ${virtualenv} --python=$(which python3.6) virtualenv
+elif [ $(which python3.8) ]; then
+    ${virtualenv} --python=$(which python3.8) virtualenv
+fi
 
 # avoid pip bugs
 ./virtualenv/bin/pip3 install --upgrade pip
